## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0 
  - stable
  - nightly
notifications:
  email:
    - github@tamasnagy.com

matrix:
 allow_failures:
 - julia: nightly

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())' 
